import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Inter } from "next/font/google";
import HomeFooter from "@/modules/home/HomeFooter";
import Navbar from "@/modules/home/HomeNav";
import HomeHeader from "@/modules/home/HomeHeader";
import HomeHeadMenu from "@/modules/home/HomeHeadMenu";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <link
        href="https://cdn.jsdelivr.net/npm/remixicon@4.3.0/fonts/remixicon.css"
        rel="stylesheet"
      />
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} font-sans antialiased m-0 p-0`}
      >
         <div className="">
        <Navbar />
      </div>
      <HomeHeader />
      {/* <HomeHeadMenu /> */}
        <HomeFooter/>
        {children}
      </body>
    </html>
  );
}
